alias ls="ls --color=auto -l"
alias lsa="ls -a"
alias aptget="sudo apt-get install"
alias aptup="sudo apt-get update"
alias gita="git add"
alias gitc="git commit"
alias gitl="git lg"
alias gitl10="git lg | head -n 10"
alias gits="git status"
alias ycm_extra_c="cp /root/.vim/sample_ycm/.ycm_extra_conf_c.py ./.ycm_extra_conf.py && vim .ycm_extra_conf.py"
alias ycm_extra_cpp="cp /root/.vim/sample_ycm/.ycm_extra_conf_cpp.py ./.ycm_extra_conf.py && vim .ycm_extra_conf.py"
